export const APP_NAME = "Esnaf Tezgahı"

export const ROUTES = {
  DASHBOARD: "/",
  UPLOAD: "/upload",
  INVENTORY: "/inventory",
  ORDERS: "/orders",
  SETTINGS: "/settings",
}


export const T = {
  tr: {
    dashboard: "Panel",
    upload: "Yükle",
    inventory: "Stok",
    orders: "Siparişler",
    settings: "Ayarlar",
    newOrder: "Yeni Sipariş",
    searchPlaceholder: "Stok ara (Enter'a bas)...",
    activeAlerts: "Aktif Uyarılar",
    agentActivity: "Ajan Aktivitesi",
    notifications: "Bildirimler",
    noAlerts: "Aktif uyarı yok. Her şey yolunda!",
    viewAll: "Panelde Tümünü Gör",
    ordersToday: "Bugünkü Siparişler",
    noActivity: "Henüz ajan aktivitesi yok. Sipariş fişi veya raf fotoğrafı yükle.",
    dismiss: "Kapat",
    email: "E-posta",
    allClear: "Tümü Tamam",
    orderSlip: "Sipariş Fişi",
    shelfScan: "Raf Tarama",
    voiceNote: "Sesli Not",
    orderSlipDesc: "JPG, PNG veya WEBP - el yazısı veya baskı",
    shelfScanDesc: "Depo rafı veya ürün teşhir fotoğrafı",
    voiceNoteDesc: "WAV, MP3 veya M4A - Türkçe veya İngilizce konuş",
    uploadTitle: "Yükle",
    uploadDesc: "Sipariş fişi, raf fotoğrafı veya sesli not bırak - gerisini ajan halleder.",
    importCsv: "CSV İçe Aktar",
    addProduct: "Ürün Ekle",
    totalProducts: "toplam ürün",
    totalOrders: "toplam sipariş",
    product: "Ürün",
    sku: "SKU",
    category: "Kategori",
    price: "Fiyat",
    stock: "Stok",
    threshold: "Eşik",
    status: "Durum",
    qty: "Adet",
    unitPrice: "Birim Fiyat",
    loading: "Yükleniyor...",
    error: "Hata",
    saving: "Kaydediliyor...",
    cancel: "İptal",
    more: "daha",
    all: "Tümü",
    retry: "Tekrar dene",
    processingComplete: "İşlem tamamlandı",
    alertsCreated: "uyarı oluşturuldu",
    uploadAnother: "Başka Dosya Yükle",
    productName: "İsim",
    initialStock: "Başlangıç Stok",
    supplierName: "Tedarikçi Adı",
    supplierEmail: "Tedarikçi E-posta",
    editProduct: "Ürünü Düzenle",
    addProductTitle: "Yeni Ürün Ekle",
    editProductDesc: "Ürün bilgilerini güncelleyin.",
    addProductDesc: "Stoğa eklemek için ürün bilgilerini girin.",
    searchFilter: "filtresi",
    nameRequired: "İsim zorunludur",
    productUpdated: "Ürün güncellendi.",
    productAdded: "Ürün stoğa eklendi.",
    productSaveFailed: "Ürün kaydedilemedi",
    saveChanges: "Değişiklikleri Kaydet",
    deleteProduct: "Ürünü Sil",
    deletedSuffix: "silindi.",
    importedSuffix: "ürün başarıyla içe aktarıldı.",
    filterCritical: "Kritik",
    filterLow: "Düşük",
    filterNormal: "Normal",
    orderFulfilled: "Sipariş tamamlandı.",
    orderCancelled: "Sipariş iptal edildi.",
    cancelOrder: "Siparişi İptal Et",
    fulfillOrder: "Siparişi Tamamla",
    settingsDesc: "AI modelini ve API kimlik bilgilerini yapılandır.",
    apiKeyNote: "API anahtarı .env dosyanızda saklanır, tarayıcıya gönderilmez.",
    savedBang: "Kaydedildi!",
    saveSettings: "Ayarları Kaydet",
    settingsSaved: "Ayarlar kaydedildi.",
    settingsSaveFailed: "Ayarlar kaydedilemedi.",
    currentModel: "Mevcut model:",
    keySet: "Ayarlandı",
    keyNotSet: "Ayarlanmadı",
    dangerZone: "Tehlikeli Bölge",
    dangerZoneDesc: "Tüm veritabanı tablolarını kalıcı olarak siler ve varsayılan verilerle yeniden doldurur.",
    resetting: "Sıfırlanıyor...",
    resetDb: "Veritabanını Sıfırla ve Yeniden Doldur",
    resetConfirmTitle: "Veritabanı Sıfırlansın mı?",
    resetConfirmMsg: "Tüm siparişler, stok ve uyarılar kalıcı olarak silinecek ve varsayılan verilerle yeniden doldurulacak. Bu işlem geri alınamaz.",
    resetFailed: "Sıfırlama başarısız:",
    hide: "Gizle",
    supplierEmailDraft: "Tedarikçi E-posta Taslağı",
    noProducts: "Henüz ürün yok",
    noProductsDesc: "Ürün ekleyin veya CSV içe aktarın.",
    noSearchResults: "Sonuç bulunamadı",
    noSearchResultsDesc: "Aramanızla eşleşen ürün yok.",
    noOrders: "Henüz sipariş yok",
    noOrdersDesc: "Sipariş fişi veya sesli not yükleyince siparişler burada görünür.",
    confirm: "Onayla",
    agentReasoning: "Ajan Analizi",
    agentThinkingCaption: "Gemini AI girdini analiz ediyor",
    uploadingFile: "Dosya yükleniyor...",
    classifyingInput: "Girdi sınıflandırılıyor...",
    runningAI: "AI analizi çalışıyor...",
    updatingRecords: "Kayıtlar güncelleniyor...",
    generatingReasoning: "Sonuç oluşturuluyor...",
    processing: "İşleniyor...",
    fontSizeLabel: "Yazı Boyutu",
    appearance: "Görünüm",
    language: "Dil",
    dark: "Koyu",
    light: "Açık",
    dashboardSubtitle: "Anadolu Doğal Kooperatifi - Operasyon Görünümü",
    apiReference: "API Referansı →",
    stockStatusLabels: { ok: "Normal", low: "Düşük", critical: "Kritik" },
    sourceLabels: { image_order: "GÖRÜNTÜ", voice: "SES", manual: "MANUEL" },
    statusLabels: { pending: "Bekliyor", fulfilled: "Tamamlandı", cancelled: "İptal" },
    alertTypeLabels: { low_stock: "Düşük Stok", critical_stock: "Kritik Stok", setup_required: "Kurulum Gerekli" },
    startRecording: "Kaydı Başlat",
    stopRecording: "Kaydı Durdur",
    micPermissionDenied: "Mikrofon erişimine izin verilmedi. Lütfen tarayıcı ayarlarını kontrol edin.",
    orUploadFile: "veya dosya yükle",
    setupWelcome: "Esnaf Tezgahı'na Hoş Geldiniz",
    setupSubtitle: "Başlamadan önce adınızı ve işletmenizi tanımlayın.",
    setupDisplayName: "Görünüm Adı",
    setupStoreName: "İşletme Adı",
    setupDisplayNamePlaceholder: "Adınız Soyadınız",
    setupStoreNamePlaceholder: "İşletmenizin Adı",
    setupSave: "Başla",
    editProfile: "Profili Düzenle",
    appSubtitle: "AI Operasyon Platformu",
    "ERR_ORDER_NOT_FOUND": "Sipariş bulunamadı",
    "ERR_PRODUCT_NOT_FOUND": "Ürün bulunamadı",
    "ERR_SKU_EXISTS": "Bu SKU'ya sahip bir ürün zaten var",
    "ERR_ONLY_CSV": "Sadece CSV dosyalarına izin verilir",
    "ERR_INVALID_CSV": "Geçersiz CSV formatı",
    "ERR_ALERT_NOT_FOUND": "Uyarı bulunamadı",
    "ERR_AI_UNAVAILABLE": "Yapay zeka modeli geçici olarak kullanılamıyor. Lütfen birazdan tekrar deneyin.",
    "ERR_IMAGE_UNIDENTIFIED": "Görüntü tanımlanamadı. Lütfen bir sipariş fişinin veya rafın net bir fotoğrafını yükleyin.",
    "ERR_INSUFFICIENT_STOCK": "Yetersiz stok:",
    "ERR_UNSUPPORTED_IMAGE": "Desteklenmeyen görüntü türü. JPEG, PNG veya WEBP kullanın.",
    "ERR_UNSUPPORTED_AUDIO": "Desteklenmeyen ses türü.",
    "ERR_AI_PARSE": "Yapay zeka yanıtı işlenemedi.",
    "ERR_NETWORK": "Ağ hatası (Sunucuya ulaşılamıyor)",
    uploadFailed: "Yükleme başarısız",
    paginationItems: "ürün",
    paginationPrev: "Önceki",
    paginationNext: "Sonraki",
    apiKeyPlaceholder: "API anahtarınızı girin",
    apiKeySetPlaceholder: "••••••••••••••••••• (ayarlandı)",
    defaultCategory: "Genel",
    modelLabel: "Model",
  },
  en: {
    dashboard: "Dashboard",
    upload: "Upload",
    inventory: "Inventory",
    orders: "Orders",
    settings: "Settings",
    newOrder: "New Order",
    searchPlaceholder: "Search inventory (press Enter)...",
    activeAlerts: "Active Alerts",
    agentActivity: "Agent Activity",
    notifications: "Notifications",
    noAlerts: "No active alerts. All clear!",
    viewAll: "View All on Dashboard",
    ordersToday: "Orders Today",
    noActivity: "No agent activity yet. Upload an order slip or shelf photo to get started.",
    dismiss: "Dismiss",
    email: "Email",
    allClear: "All Clear",
    orderSlip: "Order Slip",
    shelfScan: "Shelf Scan",
    voiceNote: "Voice Note",
    orderSlipDesc: "JPG, PNG, or WEBP - handwritten or printed",
    shelfScanDesc: "Photo of your storage shelf or product display",
    voiceNoteDesc: "WAV, MP3, or M4A - speak in Turkish or English",
    uploadTitle: "Upload",
    uploadDesc: "Drop an order slip, shelf photo, or voice note - the agent handles the rest.",
    importCsv: "Import CSV",
    addProduct: "Add Product",
    totalProducts: "total products",
    totalOrders: "total orders",
    product: "Product",
    sku: "SKU",
    category: "Category",
    price: "Price",
    stock: "Stock",
    threshold: "Threshold",
    status: "Status",
    qty: "Qty",
    unitPrice: "Unit Price",
    loading: "Loading...",
    error: "Error",
    saving: "Saving...",
    cancel: "Cancel",
    more: "more",
    all: "All",
    retry: "Try Again",
    processingComplete: "Processing complete",
    alertsCreated: "alerts created",
    uploadAnother: "Upload Another File",
    productName: "Name",
    initialStock: "Initial Stock",
    supplierName: "Supplier Name",
    supplierEmail: "Supplier Email",
    editProduct: "Edit Product",
    addProductTitle: "Add New Product",
    editProductDesc: "Update product details.",
    addProductDesc: "Enter product details to add to inventory.",
    searchFilter: "filter",
    nameRequired: "Name is required",
    productUpdated: "Product updated.",
    productAdded: "Product added to inventory.",
    productSaveFailed: "Failed to save product",
    saveChanges: "Save Changes",
    deleteProduct: "Delete Product",
    deletedSuffix: "deleted.",
    importedSuffix: "products imported successfully.",
    filterCritical: "Critical",
    filterLow: "Low",
    filterNormal: "Normal",
    orderFulfilled: "Order fulfilled.",
    orderCancelled: "Order cancelled.",
    cancelOrder: "Cancel Order",
    fulfillOrder: "Fulfill Order",
    settingsDesc: "Configure your AI model and API credentials.",
    apiKeyNote: "API key is stored in your .env file and never sent to the browser.",
    savedBang: "Saved!",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved.",
    settingsSaveFailed: "Failed to save settings.",
    currentModel: "Current model:",
    keySet: "Set",
    keyNotSet: "Not set",
    dangerZone: "Danger Zone",
    dangerZoneDesc: "Irreversibly drop all database tables and reseed with default data.",
    resetting: "Resetting...",
    resetDb: "Reset Database & Reseed",
    resetConfirmTitle: "Reset Database?",
    resetConfirmMsg: "This will permanently delete all orders, inventory, and alerts, then reseed with default data. This cannot be undone.",
    resetFailed: "Reset failed:",
    hide: "Hide",
    supplierEmailDraft: "Draft Supplier Email",
    noProducts: "No products yet",
    noProductsDesc: "Add a product or import a CSV file.",
    noSearchResults: "No results found",
    noSearchResultsDesc: "No products match your search.",
    noOrders: "No orders yet",
    noOrdersDesc: "Upload an order slip or voice note and orders will appear here.",
    confirm: "Confirm",
    agentReasoning: "Agent Reasoning",
    agentThinkingCaption: "Gemini AI is analyzing your input",
    uploadingFile: "Uploading file...",
    classifyingInput: "Classifying input...",
    runningAI: "Running AI analysis...",
    updatingRecords: "Updating records...",
    generatingReasoning: "Generating reasoning...",
    processing: "Processing...",
    fontSizeLabel: "Font Size",
    appearance: "Appearance",
    language: "Language",
    dark: "Dark",
    light: "Light",
    dashboardSubtitle: "Anadolu Doğal Kooperatifi - Operations Overview",
    apiReference: "API Reference →",
    stockStatusLabels: { ok: "Normal", low: "Low Stock", critical: "Critical Stock" },
    sourceLabels: { image_order: "IMAGE", voice: "VOICE", manual: "MANUAL" },
    statusLabels: { pending: "Pending", fulfilled: "Fulfilled", cancelled: "Cancelled" },
    alertTypeLabels: { low_stock: "Low Stock", critical_stock: "Critical Stock", setup_required: "Setup Required" },
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    micPermissionDenied: "Microphone access denied. Please check your browser settings.",
    orUploadFile: "or upload a file",
    setupWelcome: "Welcome to Esnaf Tezgahı",
    setupSubtitle: "Before we start, tell us your name and your store.",
    setupDisplayName: "Display Name",
    setupStoreName: "Store Name",
    setupDisplayNamePlaceholder: "Your Full Name",
    setupStoreNamePlaceholder: "Your Store Name",
    setupSave: "Get Started",
    editProfile: "Edit Profile",
    appSubtitle: "AI Operations Platform",
    "ERR_ORDER_NOT_FOUND": "Order not found",
    "ERR_PRODUCT_NOT_FOUND": "Product not found",
    "ERR_SKU_EXISTS": "Product with this SKU already exists",
    "ERR_ONLY_CSV": "Only CSV files are allowed",
    "ERR_INVALID_CSV": "Invalid CSV format",
    "ERR_ALERT_NOT_FOUND": "Alert not found",
    "ERR_AI_UNAVAILABLE": "AI model temporarily unavailable. Please try again in a moment.",
    "ERR_IMAGE_UNIDENTIFIED": "Could not identify the image. Please upload a clear photo of an order slip or a shelf.",
    "ERR_INSUFFICIENT_STOCK": "Insufficient stock:",
    "ERR_UNSUPPORTED_IMAGE": "Unsupported image type. Use JPEG, PNG, or WEBP.",
    "ERR_UNSUPPORTED_AUDIO": "Unsupported audio type.",
    "ERR_AI_PARSE": "Failed to parse AI response.",
    "ERR_NETWORK": "Network Error",
    uploadFailed: "Upload failed",
    paginationItems: "products",
    paginationPrev: "Previous",
    paginationNext: "Next",
    apiKeyPlaceholder: "Enter your API key",
    apiKeySetPlaceholder: "••••••••••••••••••• (key is set)",
    defaultCategory: "General",
    modelLabel: "Model",
  }
}
