export const APP_NAME = "Esnaf Tezgahı"

export const ROUTES = {
  DASHBOARD: "/",
  UPLOAD: "/upload",
  INVENTORY: "/inventory",
  ORDERS: "/orders",
  SETTINGS: "/settings",
}

export const SOURCE_LABELS = {
  image_order: "GÖRÜNTÜ",
  voice: "SES",
  manual: "MANUEL",
}

export const STATUS_LABELS = {
  pending: "Bekliyor",
  fulfilled: "Tamamlandı",
  cancelled: "İptal",
}

export const STOCK_STATUS_LABELS = {
  ok: "Normal",
  low: "Düşük",
  critical: "Kritik",
}

export const ALERT_TYPE_LABELS = {
  low_stock: "Düşük Stok",
  critical_stock: "Kritik Stok",
  setup_required: "Kurulum Gerekli",
}

export const T = {
  tr: {
    dashboard: "Panel",
    upload: "Yükle",
    inventory: "Stok",
    orders: "Siparişler",
    settings: "Ayarlar",
    newOrder: "Yeni Sipariş",
    searchPlaceholder: "Stok ara (Enter'a bas)...",
    activeAlerts: "Aktif Uyarılar",
    agentActivity: "Ajan Aktivitesi",
    notifications: "Bildirimler",
    noAlerts: "Aktif uyarı yok. Her şey yolunda!",
    viewAll: "Panelde Tümünü Gör",
    ordersToday: "Bugünkü Siparişler",
    noActivity: "Henüz ajan aktivitesi yok. Sipariş fişi veya raf fotoğrafı yükle.",
    dismiss: "Kapat",
    email: "E-posta",
    allClear: "Tümü Tamam",
    orderSlip: "Sipariş Fişi",
    shelfScan: "Raf Tarama",
    voiceNote: "Sesli Not",
    orderSlipDesc: "JPG, PNG veya WEBP - el yazısı veya baskı",
    shelfScanDesc: "Depo rafı veya ürün teşhir fotoğrafı",
    voiceNoteDesc: "WAV, MP3 veya M4A - Türkçe veya İngilizce konuş",
    uploadTitle: "Yükle",
    uploadDesc: "Sipariş fişi, raf fotoğrafı veya sesli not bırak - gerisini ajan halleder.",
    importCsv: "CSV İçe Aktar",
    addProduct: "Ürün Ekle",
    totalProducts: "toplam ürün",
    totalOrders: "toplam sipariş",
    product: "Ürün",
    sku: "SKU",
    category: "Kategori",
    price: "Fiyat",
    stock: "Stok",
    threshold: "Eşik",
    status: "Durum",
    qty: "Adet",
    unitPrice: "Birim Fiyat",
    loading: "Yükleniyor...",
    error: "Hata",
    saving: "Kaydediliyor...",
    cancel: "İptal",
    more: "daha",
    all: "Tümü",
    retry: "Tekrar dene",
    processingComplete: "İşlem tamamlandı",
    alertsCreated: "uyarı oluşturuldu",
    uploadAnother: "Başka Dosya Yükle",
    productName: "İsim",
    initialStock: "Başlangıç Stok",
    supplierName: "Tedarikçi Adı",
    supplierEmail: "Tedarikçi E-posta",
    editProduct: "Ürünü Düzenle",
    addProductTitle: "Yeni Ürün Ekle",
    editProductDesc: "Ürün bilgilerini güncelleyin.",
    addProductDesc: "Stoğa eklemek için ürün bilgilerini girin.",
    searchFilter: "filtresi",
    nameRequired: "İsim zorunludur",
    productUpdated: "Ürün güncellendi.",
    productAdded: "Ürün stoğa eklendi.",
    productSaveFailed: "Ürün kaydedilemedi",
    saveChanges: "Değişiklikleri Kaydet",
    deleteProduct: "Ürünü Sil",
    deletedSuffix: "silindi.",
    importedSuffix: "ürün başarıyla içe aktarıldı.",
    filterCritical: "Kritik",
    filterLow: "Düşük",
    filterNormal: "Normal",
    orderFulfilled: "Sipariş tamamlandı.",
    orderCancelled: "Sipariş iptal edildi.",
    cancelOrder: "Siparişi İptal Et",
    fulfillOrder: "Siparişi Tamamla",
    settingsDesc: "AI modelini ve API kimlik bilgilerini yapılandır.",
    apiKeyNote: "API anahtarı .env dosyanızda saklanır, tarayıcıya gönderilmez.",
    savedBang: "Kaydedildi!",
    saveSettings: "Ayarları Kaydet",
    settingsSaved: "Ayarlar kaydedildi.",
    settingsSaveFailed: "Ayarlar kaydedilemedi.",
    currentModel: "Mevcut model:",
    keySet: "Ayarlandı",
    keyNotSet: "Ayarlanmadı",
    dangerZone: "Tehlikeli Bölge",
    dangerZoneDesc: "Tüm veritabanı tablolarını kalıcı olarak siler ve varsayılan verilerle yeniden doldurur.",
    resetting: "Sıfırlanıyor...",
    resetDb: "Veritabanını Sıfırla ve Yeniden Doldur",
    resetConfirmTitle: "Veritabanı Sıfırlansın mı?",
    resetConfirmMsg: "Tüm siparişler, stok ve uyarılar kalıcı olarak silinecek ve varsayılan verilerle yeniden doldurulacak. Bu işlem geri alınamaz.",
    resetFailed: "Sıfırlama başarısız:",
  },
  en: {
    dashboard: "Dashboard",
    upload: "Upload",
    inventory: "Inventory",
    orders: "Orders",
    settings: "Settings",
    newOrder: "New Order",
    searchPlaceholder: "Search inventory (press Enter)...",
    activeAlerts: "Active Alerts",
    agentActivity: "Agent Activity",
    notifications: "Notifications",
    noAlerts: "No active alerts. All clear!",
    viewAll: "View All on Dashboard",
    ordersToday: "Orders Today",
    noActivity: "No agent activity yet. Upload an order slip or shelf photo to get started.",
    dismiss: "Dismiss",
    email: "Email",
    allClear: "All Clear",
    orderSlip: "Order Slip",
    shelfScan: "Shelf Scan",
    voiceNote: "Voice Note",
    orderSlipDesc: "JPG, PNG, or WEBP - handwritten or printed",
    shelfScanDesc: "Photo of your storage shelf or product display",
    voiceNoteDesc: "WAV, MP3, or M4A - speak in Turkish or English",
    uploadTitle: "Upload",
    uploadDesc: "Drop an order slip, shelf photo, or voice note - the agent handles the rest.",
    importCsv: "Import CSV",
    addProduct: "Add Product",
    totalProducts: "total products",
    totalOrders: "total orders",
    product: "Product",
    sku: "SKU",
    category: "Category",
    price: "Price",
    stock: "Stock",
    threshold: "Threshold",
    status: "Status",
    qty: "Qty",
    unitPrice: "Unit Price",
    loading: "Loading...",
    error: "Error",
    saving: "Saving...",
    cancel: "Cancel",
    more: "more",
    all: "All",
    retry: "Try Again",
    processingComplete: "Processing complete",
    alertsCreated: "alerts created",
    uploadAnother: "Upload Another File",
    productName: "Name",
    initialStock: "Initial Stock",
    supplierName: "Supplier Name",
    supplierEmail: "Supplier Email",
    editProduct: "Edit Product",
    addProductTitle: "Add New Product",
    editProductDesc: "Update product details.",
    addProductDesc: "Enter product details to add to inventory.",
    searchFilter: "filter",
    nameRequired: "Name is required",
    productUpdated: "Product updated.",
    productAdded: "Product added to inventory.",
    productSaveFailed: "Failed to save product",
    saveChanges: "Save Changes",
    deleteProduct: "Delete Product",
    deletedSuffix: "deleted.",
    importedSuffix: "products imported successfully.",
    filterCritical: "Critical",
    filterLow: "Low",
    filterNormal: "Normal",
    orderFulfilled: "Order fulfilled.",
    orderCancelled: "Order cancelled.",
    cancelOrder: "Cancel Order",
    fulfillOrder: "Fulfill Order",
    settingsDesc: "Configure your AI model and API credentials.",
    apiKeyNote: "API key is stored in your .env file and never sent to the browser.",
    savedBang: "Saved!",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved.",
    settingsSaveFailed: "Failed to save settings.",
    currentModel: "Current model:",
    keySet: "Set",
    keyNotSet: "Not set",
    dangerZone: "Danger Zone",
    dangerZoneDesc: "Irreversibly drop all database tables and reseed with default data.",
    resetting: "Resetting...",
    resetDb: "Reset Database & Reseed",
    resetConfirmTitle: "Reset Database?",
    resetConfirmMsg: "This will permanently delete all orders, inventory, and alerts, then reseed with default data. This cannot be undone.",
    resetFailed: "Reset failed:",
  }
}
